name: Push a Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print working directory
        run: pwd   
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r /home/runner/work/m6-mp1b-docker-actions/m6-mp1b-docker-actions/bikeshare_project/requirements/requirements.txt

      - name: Train and save pipeline
        run: python /home/runner/work/m6-mp1b-docker-actions/m6-mp1b-docker-actions/bikeshare_project/bikeshare_model/train_pipeline.py

      - name: Upload trained pipeline
        uses: actions/upload-artifact@v4
        with:
          name: my-trained-pipeline
          path: /home/runner/work/m6-mp1b-docker-actions/m6-mp1b-docker-actions/bikeshare_project/bikeshare_model/trained_models/*.pkl
          retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Download trained pipeline
        uses: actions/download-artifact@v2
        with:
          name: my-trained-pipeline
          path: /home/runner/work/m6-mp1b-docker-actions/m6-mp1b-docker-actions/bikeshare_project/bikeshare_model/trained_models

      - name: Install dependencies
        run: pip install -r /home/runner/work/m6-mp1b-docker-actions/m6-mp1b-docker-actions/bikeshare_project/requirements/test_requirements.txt

      - name: Test with pytest
        run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Download trained pipeline
        uses: actions/download-artifact@v2
        with:
          name: my-trained-pipeline
          path: bikeshare_model/trained_models

      - name: Install dependencies
        run: pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Upload build package
        uses: actions/upload-artifact@v2
        with:
          name: my-build-package
          path: dist/*.whl
          retention-days: 1

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build package
        uses: actions/download-artifact@v2
        with:
          name: my-build-package
          path: bike_sharing_api

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker image for FastAPI app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker build . -f Dockerfile -t $DOCKER_USER/bike_sharing_api:latest

      - name: Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER/bike_sharing_api

      - name: Logout from Docker Hub
        run: docker logout
